import json
import os
import re
import math
import sys

class SmartScoreParser:
    """
    Handles parsing raw JSON and text artifacts generated by Slither, Solidity files, and Hardhat.
    Designed with robust fallback behaviors to prevent pipelines from breaking.
    """

    @staticmethod
    def parse_slither_json(filepath: str) -> dict:
        """
        Parses Slither's JSON output to count high-severity vulnerabilities (V) and invariant violations (IV).
        """
        results = {"V": 0, "IV": 0}
        
        if not filepath:
            print("⚠️ No Slither JSON filepath provided. Using default metrics (0 vulnerabilities).", file=sys.stderr)
            return results

        if not os.path.exists(filepath):
            print(f"⚠️ Slither JSON file not found at: {filepath}. Using default metrics (0 vulnerabilities).", file=sys.stderr)
            return results

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)

            # 1. Parse vulnerabilities from the 'results.detectors' array
            detectors = data.get("results", {}).get("detectors", [])
            high_vulns = 0
            for d in detectors:
                impact = d.get("impact", "").lower()
                if impact == "high":
                    high_vulns += 1
            results["V"] = high_vulns

            # 2. Parse invariant violations (IV)
            # Standard Slither doesn't output a top-level 'contracts' key in the detector JSON output.
            # However, we support it here if it exists (preserving/enhancing original logic).
            contracts = data.get("contracts", [])
            iv_count = 0
            for contract in contracts:
                for function in contract.get("functions", []):
                    unreachable = function.get("unreachable_statements", [])
                    if unreachable:
                        iv_count += len(unreachable)
            results["IV"] = iv_count

        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"⚠️ Error parsing Slither JSON: {e}. Defaulting to 0 vulnerabilities/invariants.", file=sys.stderr)

        return results

    @staticmethod
    def estimate_time_complexity(solidity_path: str) -> int:
        """
        Parses Solidity source file using regex to extract functions and loops (for, while).
        Computes categorical time complexity on a scale of [1, 5].
        """
        default_complexity = 1
        
        if not solidity_path or not os.path.exists(solidity_path):
            print(f"⚠️ Solidity source file not found at: {solidity_path}. Defaulting complexity to 1.", file=sys.stderr)
            return default_complexity

        try:
            with open(solidity_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Remove comments to avoid false positive matches
            content = re.sub(r'//.*', '', content)
            content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)

            # Find constructor and functions
            funcs = re.findall(r'\b(function|constructor)\b', content)
            num_funcs = len(funcs)

            if num_funcs == 0:
                return default_complexity

            # Count loop occurrences: 'for' or 'while'
            loops = re.findall(r'\b(for|while)\b', content)
            num_loops = len(loops)

            # Calculate average complexity: base level 1 + loops ratio
            avg_complexity = 1.0 + (num_loops / num_funcs)

            # Scale to categorical ranges [1, 5] matching academic config:
            if avg_complexity < 3.0:
                return 1
            elif avg_complexity < 6.0:
                return 2
            elif avg_complexity < 10.0:
                return 3
            elif avg_complexity < 15.0:
                return 4
            else:
                return 5

        except Exception as e:
            print(f"⚠️ Error reading Solidity file for complexity analysis: {e}. Defaulting complexity to 1.", file=sys.stderr)
            return default_complexity

    @staticmethod
    def parse_hardhat_gas(filepath: str) -> dict:
        """
        Parses gasReporterOutput.json to calculate the average gas per function (GF) and gas variance (GV).
        """
        results = {"GF": None, "GV": None}
        
        if not filepath or not os.path.exists(filepath):
            # Log warning, let CLI fallback to defaults or overrides
            return results

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)

            # Extract methods data
            methods = data.get("data", {}).get("methods", {})
            if not methods:
                print("⚠️ Hardhat gas reporter JSON found, but data.methods is empty.", file=sys.stderr)
                return results

            gas_values = []
            for method_key, method_val in methods.items():
                gas_data = method_val.get("gasData", [])
                # Filter out null or non-numeric entries
                gas_values.extend([g for g in gas_data if isinstance(g, (int, float))])

            if not gas_values:
                print("⚠️ Hardhat gas reporter JSON found, but no gas measurements were found in tests.", file=sys.stderr)
                return results

            # Compute average gas cost per function execution (GF)
            gf = sum(gas_values) / len(gas_values)
            
            # Compute gas variance (GV)
            mean = gf
            variance = sum((x - mean) ** 2 for x in gas_values) / len(gas_values)

            results["GF"] = gf
            results["GV"] = variance

        except Exception as e:
            print(f"⚠️ Error parsing Hardhat gas report JSON: {e}. Hardhat gas reporter will be bypassed.", file=sys.stderr)

        return results
